# -*- coding: utf-8 -*-
"""knock74.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZeO0_h94ZCWO9FI-PX20aipjJKlZLGvv
"""

#knock70-79.ipynbを参照