dataset:
	wget https://archive.ics.uci.edu/ml/machine-learning-databases/00359/NewsAggregatorDataset.zip
	unzip NewsAggregatorDataset.zip
	sed -e 's/"/'\''/g' ./newsCorpora.csv > ./newsCorpora_re.csv
	rm NewsAggregatorDataset.zip
