# -*- coding: utf-8 -*-
"""knock43.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kiO2WRT1FCxCMhZtEJIuGm5pRt1GMjte
"""

#knock40-49.ipynb参照