# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14DqeV_dgHA6-g-eX63L3ts9ZO475iETJ
"""

#knock60-69.ipynbを参照