# -*- coding: utf-8 -*-
"""knock50.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wdZbftyI_HkomyCHdYoDVx9tfrqL_1KT
"""

#空ファイルです、knock50-59.ipynbを参照ください