dataset:
	curl https://nlp100.github.io/data/popular-names.txt > popular-names.txt

executable:
	chmod +x knock10.sh
	chmod +x knock11.sh
	chmod +x knock12.sh
	chmod +x knock13.sh
	chmod +x knock14.sh
	chmod +x knock15.sh
	chmod +x knock16.sh
	chmod +x knock17.sh
	chmod +x knock18.sh
	chmod +x knock19.sh

clean:
	rm *.txt
	rm sp*
