# -*- coding: utf-8 -*-
"""knock80.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hjgldPO-eEMS5vTzrB5xTFb1w0j3TQTz
"""

#knock80-89.ipynbを参考にすること。